export const LAU_MAJORS = [
  'Architecture',
  'Bioinformatics',
  'Biology',
  'Business Studies',
  'Chemistry',
  'Civil Engineering',
  'Communication',
  'Computer Engineering',
  'Computer Science',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Fashion Design',
  'Fine Arts',
  'Graphic Design',
  'Hospitality and Tourism Management',
  'Industrial Engineering',
  'Interior Design',
  'Mathematics',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Multimedia Journalism',
  'Nursing',
  'Nutrition and Dietetics',
  'Nutrition and Dietetics Coordinated Program',
  'Performing Arts',
  'Petroleum Engineering',
  'Pharmacy',
  'Political Science/International Affairs',
  'Psychology',
  'Translation',
  'Television and Film',
];

export const API_URL = 'http://192.168.1.106:3000';
